services:
  zfs-guardian:
    build: .
    container_name: zfs-guardian
    privileged: true
    restart: unless-stopped
    ports:
      - "48080:8000"
    volumes:
      - ./data:/app/data                        # Guarda la BD, configs e idiomas
      - /dev/disk/by-id:/dev/disk/by-id:ro      # Necesario para mapeo persistente ZFS
      - /sys/class/hwmon:/sys/class/hwmon:rw    # Necesario para inyectar voltaje PWM e i2c
    environment:
      - TZ=Europe/Madrid    # Cambia esto si es necesario
